name: Streak
on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run commit script
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git commit --allow-empty -m "Streak grass: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
